# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyFirstiOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyFirstiOS
	pod 'lottie-ios'

	target 'MyFirstiOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyFirstiOSUITests' do
    # Pods for testing
  end

end
